2025-01-09 19:36:34.202 | ERROR    | utils.ClientLogManager:log:48 - Import tbk error! Error: module 'types' has no attribute 'ModuleType', occurred on line 30 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/grpc/_runtime_protos.py
2025-01-09 19:37:59.123 | ERROR    | utils.ClientLogManager:log:48 - Import tbk error! Error: module 'types' has no attribute 'ModuleType', occurred on line 30 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/grpc/_runtime_protos.py
2025-01-09 19:39:31.456 | ERROR    | utils.ClientLogManager:log:48 - Import tbk error! Error: module 'types' has no attribute 'ModuleType', occurred on line 30 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/grpc/_runtime_protos.py
2025-01-09 19:39:58.686 | ERROR    | utils.ClientLogManager:log:48 - Import tbk error! Error: module 'types' has no attribute 'ModuleType', occurred on line 30 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/grpc/_runtime_protos.py
2025-01-09 20:20:49.092 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.102 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.112 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.122 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.132 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.142 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.152 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.162 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.172 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.182 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:20:49.192 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.705 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.715 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.725 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.735 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.745 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.756 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.766 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.776 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.786 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.796 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:21:10.806 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.244 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.254 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.264 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.274 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.284 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.295 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.305 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.315 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.325 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.340 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:00.347 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.200 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.209 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.220 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.230 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.240 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.250 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.260 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.270 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.280 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.290 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
2025-01-09 20:45:15.300 | ERROR    | utils.ClientLogManager:log:48 - error Error: Field number 0 is illegal., occurred on line 1233 in file /home/mark/anaconda3/envs/platform_war/lib/python3.11/site-packages/google/protobuf/internal/python_message.py
